// Seed content for the Community tab.
import type {
  CommunityPost,
  ForumThread,
  CityAlert,
  Poll,
  LostFoundItem,
  Memory,
} from "./types";

function ago(hours: number): string {
  return new Date(Date.now() - hours * 3600_000).toISOString();
}

export const seedPosts: CommunityPost[] = [
  {
    id: "po1",
    type: "issue",
    category: "water",
    title: "Ward 12 me paani kab tak aayega?",
    body: "Subah se supply band hai. Nagar Nigam ka koi update? Tanker mangwana padega kya?",
    author: "Satna Resident",
    neighborhood: "Ward 12",
    is_anonymous: true,
    like_count: 24,
    comment_count: 11,
    created_at: ago(3),
  },
  {
    id: "po2",
    type: "tip",
    category: "general",
    title: "Maihar jaane walo ke liye — ropeway tickets online le lo",
    body: "Navratri se pehle hi counter pe 1-2 ghante ki line lag rahi hai. Online booking se seedha entry milti hai.",
    author: "Ramesh Gupta",
    neighborhood: "Civil Lines",
    is_anonymous: false,
    like_count: 56,
    comment_count: 8,
    created_at: ago(7),
  },
  {
    id: "po3",
    type: "question",
    category: "roads",
    title: "Rewa Road ka flyover kab complete hoga?",
    body: "Roz ka jam ho gaya hai. Kisi ko official timeline pata hai?",
    author: "Anita Singh",
    neighborhood: "Rewa Road",
    is_anonymous: false,
    like_count: 31,
    comment_count: 19,
    created_at: ago(12),
  },
  {
    id: "po4",
    type: "appreciation",
    category: "events",
    title: "Kal ka kavi sammelan shaandar tha 👏",
    body: "Town Hall me bahut achha program hua. Organisers ko dhanyavaad — aur hone chahiye aise events.",
    author: "Deepak Mishra",
    neighborhood: "Dhawari",
    is_anonymous: false,
    like_count: 42,
    comment_count: 5,
    created_at: ago(26),
  },
  {
    id: "po5",
    type: "question",
    category: "help",
    title: "Blood donor chahiye — B+ urgently",
    body: "District Hospital me admit patient ke liye. Contact via comments, main coordinate kar dunga.",
    author: "Sahil Khan",
    neighborhood: "Mukhtiyarganj",
    is_anonymous: false,
    like_count: 67,
    comment_count: 23,
    created_at: ago(5),
  },
];

export const postCategories = [
  { key: "all", en: "All", hi: "सभी" },
  { key: "roads", en: "Roads", hi: "सड़कें" },
  { key: "water", en: "Water", hi: "पानी" },
  { key: "electricity", en: "Electricity", hi: "बिजली" },
  { key: "events", en: "Events", hi: "कार्यक्रम" },
  { key: "business", en: "Business", hi: "व्यापार" },
  { key: "general", en: "General", hi: "सामान्य" },
  { key: "help", en: "Help needed", hi: "मदद चाहिए" },
];

export const forumBoards = [
  { slug: "city-development", name: "City Development Ideas", hi: "शहर विकास के विचार", emoji: "🏗️", desc: "Suggest improvements to Satna" },
  { slug: "tourism-heritage", name: "Tourism & Heritage", hi: "पर्यटन व धरोहर", emoji: "🪷", desc: "Trails, places, preservation" },
  { slug: "business-jobs", name: "Business & Jobs", hi: "व्यापार व नौकरियाँ", emoji: "💼", desc: "Local opportunities, classifieds" },
  { slug: "education", name: "Education", hi: "शिक्षा", emoji: "📚", desc: "Schools, coaching, results" },
  { slug: "festivals-events", name: "Festivals & Events", hi: "त्योहार व कार्यक्रम", emoji: "🎉", desc: "Planning, volunteer coordination" },
  { slug: "sports-youth", name: "Sports & Youth", hi: "खेल व युवा", emoji: "🏏", desc: "Cricket, kabaddi, local leagues" },
  { slug: "ask-a-local", name: "Ask a Local", hi: "स्थानीय से पूछें", emoji: "🙋", desc: "Outsiders asking residents anything" },
  { slug: "dine-together-stories", name: "Dine Together Stories", hi: "साथ खाने के किस्से", emoji: "🍽️", desc: "Share how a dining meetup went" },
  { slug: "cab-share-coordination", name: "Cab Share Coordination", hi: "कैब शेयर समन्वय", emoji: "🚖", desc: "Routes, timing, trusted companions" },
];

export const seedThreads: ForumThread[] = [
  { id: "th1", board_slug: "city-development", title: "Satna ko ek proper city bus service chahiye — route map draft", author: "Nilesh P.", reply_count: 34, last_active: "2 hrs ago", is_pinned: true },
  { id: "th2", board_slug: "city-development", title: "Riverfront development at Satna ghats — ideas?", author: "Kavita J.", reply_count: 12, last_active: "1 day ago", is_pinned: false },
  { id: "th3", board_slug: "tourism-heritage", title: "Bharhut deserves a national-level museum upgrade", author: "Dr. Verma", reply_count: 21, last_active: "5 hrs ago", is_pinned: true },
  { id: "th4", board_slug: "business-jobs", title: "Hiring: 2 accountants for cement dealership (Rewa Road)", author: "SK Traders", reply_count: 6, last_active: "3 hrs ago", is_pinned: false },
  { id: "th5", board_slug: "education", title: "Best maths coaching for class 11-12?", author: "Parent2026", reply_count: 18, last_active: "30 min ago", is_pinned: false },
  { id: "th6", board_slug: "ask-a-local", title: "Visiting for Maihar Mela — where to stay, Satna ya Maihar?", author: "TravellerVK", reply_count: 15, last_active: "1 hr ago", is_pinned: false },
  { id: "th7", board_slug: "dine-together-stories", title: "Met 3 strangers at Krishna Dhaba — now we're a Sunday lunch group!", author: "Rahul C.", reply_count: 9, last_active: "4 hrs ago", is_pinned: true },
  { id: "th8", board_slug: "cab-share-coordination", title: "Weekly Satna→Rewa commuters — let's make a fixed pool", author: "Priya N.", reply_count: 27, last_active: "20 min ago", is_pinned: false },
  { id: "th9", board_slug: "festivals-events", title: "Volunteers needed for Navratri pandal cleanliness drive", author: "SevaSamiti", reply_count: 11, last_active: "6 hrs ago", is_pinned: false },
  { id: "th10", board_slug: "sports-youth", title: "Inter-ward cricket — Ward 7 team registration open", author: "Captain07", reply_count: 8, last_active: "2 days ago", is_pinned: false },
];

export const seedAlerts: CityAlert[] = [
  {
    id: "al1",
    severity: "civic",
    headline: "Water supply disruption in Ward 12",
    description: "Pipeline repair near Dhawari Chowk. Supply expected to resume by 6 PM today. Tankers arranged for Gali No. 3-5.",
    affected_area: "Ward 12, Dhawari",
    source_verified: true,
    created_at: ago(4),
  },
  {
    id: "al2",
    severity: "disruption",
    headline: "Traffic diversion on Rewa Road this weekend",
    description: "Flyover girder work Sat-Sun 10 PM to 6 AM. Use bypass via Sherganj for intercity travel.",
    affected_area: "Rewa Road",
    source_verified: true,
    created_at: ago(9),
  },
  {
    id: "al3",
    severity: "good_news",
    headline: "New LED streetlights installed in Mukhtiyarganj",
    description: "120 smart LED lights now active. Report faults on the Nagar Nigam helpline.",
    affected_area: "Mukhtiyarganj",
    source_verified: false,
    created_at: ago(30),
  },
];

export const seedPolls: Poll[] = [
  {
    id: "pl1",
    question: "Which road needs repair most urgently?",
    options: [
      { id: "o1", label: "Rewa Road service lane", votes: 142 },
      { id: "o2", label: "Station Road", votes: 89 },
      { id: "o3", label: "Dhawari main market road", votes: 117 },
      { id: "o4", label: "Panna Naka crossing", votes: 64 },
    ],
    closes_in_days: 3,
  },
  {
    id: "pl2",
    question: "Best time for a Satna Mahotsav (city festival)?",
    options: [
      { id: "o1", label: "After Diwali (Nov)", votes: 201 },
      { id: "o2", label: "Winter (Dec–Jan)", votes: 174 },
      { id: "o3", label: "Holi season (Mar)", votes: 93 },
    ],
    closes_in_days: 5,
  },
];

export const seedLostFound: LostFoundItem[] = [
  {
    id: "lf1",
    type: "lost",
    category: "documents",
    title: "Lost: file with land papers + Aadhaar",
    description: "Blue plastic file, lost near Collectorate gate on Tuesday. Reward for return.",
    location: "Collectorate area",
    status: "open",
    created_at: ago(20),
  },
  {
    id: "lf2",
    type: "found",
    category: "valuables",
    title: "Found: ladies purse at bus stand",
    description: "Found near platform 2 ticket window. Describe contents to claim — deposited with police chowki.",
    location: "Satna Bus Stand",
    status: "open",
    created_at: ago(8),
  },
  {
    id: "lf3",
    type: "lost",
    category: "pets",
    title: "Missing: brown pomeranian 'Sheru'",
    description: "Last seen near Civil Lines park, red collar. Very friendly, responds to name.",
    location: "Civil Lines",
    status: "resolved",
    created_at: ago(72),
  },
];

export const seedMemories: Memory[] = [
  {
    id: "me1",
    type: "photo",
    era: "era_1980s_90s",
    caption: "Satna Junction ka purana platform, 1987 — bhaap ke engine ke aakhri saal.",
    year_estimate: 1987,
    location_tag: "Satna Junction",
    contributor: "R.K. Shrivastava",
    like_count: 134,
    remember_count: 41,
    comment_count: 17,
    is_featured: true,
  },
  {
    id: "me2",
    type: "story",
    era: "era_1950s_70s",
    caption: "Jab Maihar me Baba Allauddin Khan ka riyaaz sunai deta tha",
    story:
      "Mere dadaji batate the ki subah 4 baje Maihar ki galiyon me Baba ka sarod sunai deta tha. Log kehte the — jab tak Baba ka riyaaz na ho, Maihar ki subah shuru nahi hoti. Wo awaaz aaj bhi unke kaano me hai.",
    year_estimate: 1965,
    location_tag: "Maihar",
    contributor: "Asha Tripathi",
    like_count: 208,
    remember_count: 73,
    comment_count: 29,
    is_featured: false,
  },
  {
    id: "me3",
    type: "then_vs_now",
    era: "era_2000s",
    caption: "Dhawari Chowk — 2004 vs aaj. Cycle riksha se e-riksha tak.",
    year_estimate: 2004,
    location_tag: "Dhawari Chowk",
    contributor: "Mohit Jain",
    like_count: 96,
    remember_count: 28,
    comment_count: 12,
    is_featured: false,
  },
  {
    id: "me4",
    type: "photo",
    era: "pre_1947",
    caption: "Bharhut khudai ke samay ka durlabh chitra — ASI archive se (1873 ki khudai ka punarmudran).",
    year_estimate: 1935,
    location_tag: "Bharhut",
    contributor: "Heritage Club Satna",
    like_count: 187,
    remember_count: 12,
    comment_count: 21,
    is_featured: false,
  },
  {
    id: "me5",
    type: "story",
    era: "era_1980s_90s",
    caption: "Purane city market ki Diwali",
    story:
      "90s me city market ki Diwali alag hi hoti thi. Mitti ke diye, hath se bani mithai, aur har dukaan pe muft me milta tha ek laddu. Crackers ki dukaan ke bahar line lagti thi subah se.",
    year_estimate: 1994,
    location_tag: "Old City Market",
    contributor: "Satna Resident",
    like_count: 145,
    remember_count: 67,
    comment_count: 19,
    is_featured: false,
  },
  {
    id: "me6",
    type: "photo",
    era: "recent",
    caption: "2019 ki baarish me ghats — jab nadi phir se jawan ho gayi thi.",
    year_estimate: 2019,
    location_tag: "Satna River Ghats",
    contributor: "Photowala Satna",
    like_count: 88,
    remember_count: 15,
    comment_count: 7,
    is_featured: false,
  },
];

export const eraLabels: Record<string, { en: string; hi: string }> = {
  all: { en: "All eras", hi: "सभी दौर" },
  pre_1947: { en: "Pre-1947", hi: "1947 से पहले" },
  era_1950s_70s: { en: "1950s–70s", hi: "1950–70 का दशक" },
  era_1980s_90s: { en: "1980s–90s", hi: "1980–90 का दशक" },
  era_2000s: { en: "2000s", hi: "2000 का दशक" },
  recent: { en: "Recent", hi: "हाल के" },
};
