// Local mirror of supabase/seed.sql — used as fallback when Supabase
// env vars are not configured, so the app runs out of the box.
import type {
  Place,
  Restaurant,
  MenuItem,
  CityEvent,
  Review,
  LivePulseItem,
} from "./types";

export const seedPlaces: Place[] = [
  {
    id: "p1",
    slug: "maihar-devi-mandir",
    name_en: "Maihar Devi Mandir",
    name_hi: "मैहर देवी मंदिर",
    category: "religious",
    description_en:
      "The famous Sharda Devi temple atop Trikuta hill in Maihar. One of the most revered Shakti Peethas of the region, reachable by 1063 steps or ropeway.",
    hero_image_url: null,
    tags: ["pilgrim-friendly", "parking available", "ropeway"],
    timing: "5:00 AM – 9:00 PM",
    entry_fee: "Free (ropeway ₹120 return)",
    best_time: "Sunrise; Navratri for the mela",
    distance_km: 35,
    is_featured: true,
    avg_rating: 4.8,
    review_count: 214,
  },
  {
    id: "p2",
    slug: "bharhut-stupa-museum",
    name_en: "Bharhut Stupa Archaeological Museum",
    name_hi: "भरहुत स्तूप संग्रहालय",
    category: "heritage",
    description_en:
      "Home to fragments of the 2nd-century BCE Bharhut Stupa, among the earliest Buddhist art in India. The famous railings and gateway carvings were discovered here in 1873.",
    hero_image_url: null,
    tags: ["heritage", "guided tours", "wheelchair accessible"],
    timing: "10:00 AM – 5:00 PM (closed Mondays)",
    entry_fee: "₹20 (Indians)",
    best_time: "Winter mornings",
    distance_km: 12,
    is_featured: true,
    avg_rating: 4.6,
    review_count: 87,
  },
  {
    id: "p3",
    slug: "satna-junction",
    name_en: "Satna Junction Railway Station",
    name_hi: "सतना जंक्शन",
    category: "infrastructure",
    description_en:
      "The gateway to Satna — a major junction on the Mumbai–Howrah line connecting the city to Jabalpur, Prayagraj, Bhopal and Delhi.",
    hero_image_url: null,
    tags: ["parking available", "24x7"],
    timing: "24 hours",
    entry_fee: "Free",
    best_time: "Anytime",
    distance_km: 1.5,
    is_featured: true,
    avg_rating: 4.0,
    review_count: 156,
  },
  {
    id: "p4",
    slug: "chitrakoot",
    name_en: "Chitrakoot",
    name_hi: "चित्रकूट",
    category: "religious",
    description_en:
      "The sacred town where Lord Rama spent years of exile. Kamadgiri parikrama, Ramghat aarti and Hanuman Dhara — a full-day pilgrimage from Satna.",
    hero_image_url: null,
    tags: ["pilgrim-friendly", "day trip"],
    timing: "Open always",
    entry_fee: "Free",
    best_time: "Diwali (Deepdaan Mela)",
    distance_km: 75,
    is_featured: true,
    avg_rating: 4.7,
    review_count: 310,
  },
  {
    id: "p5",
    slug: "bhadra-waterfall",
    name_en: "Bhadra Waterfall",
    name_hi: "भद्रा जलप्रपात",
    category: "nature",
    description_en:
      "A monsoon waterfall on the Chitrakoot district boundary, surrounded by Vindhya forest. Popular picnic spot from July to October.",
    hero_image_url: null,
    tags: ["monsoon special", "trekking"],
    timing: "Daylight hours",
    entry_fee: "Free",
    best_time: "July–October",
    distance_km: 55,
    is_featured: false,
    avg_rating: 4.3,
    review_count: 42,
  },
  {
    id: "p6",
    slug: "satna-river-ghats",
    name_en: "Satna River Ghats",
    name_hi: "सतना नदी घाट",
    category: "religious",
    description_en:
      "The ghats along the Satna (Sutna) river — morning aarti, Chhath Puja gatherings and evening walks.",
    hero_image_url: null,
    tags: ["pilgrim-friendly", "evening walks"],
    timing: "Open always",
    entry_fee: "Free",
    best_time: "Early morning",
    distance_km: 3,
    is_featured: false,
    avg_rating: 4.1,
    review_count: 38,
  },
  {
    id: "p7",
    slug: "vindhyachal-temple",
    name_en: "Vindhyachal Temple",
    name_hi: "विंध्याचल मंदिर",
    category: "religious",
    description_en:
      "Ancient temple in the Vindhya foothills near Satna, dedicated to Vindhyavasini Devi.",
    hero_image_url: null,
    tags: ["pilgrim-friendly"],
    timing: "6:00 AM – 8:00 PM",
    entry_fee: "Free",
    best_time: "Navratri",
    distance_km: 18,
    is_featured: false,
    avg_rating: 4.4,
    review_count: 29,
  },
  {
    id: "p8",
    slug: "acc-cement-plant",
    name_en: "ACC Cement Plant (Kymore Belt)",
    name_hi: "एसीसी सीमेंट संयंत्र",
    category: "infrastructure",
    description_en:
      "Satna is one of India's biggest cement hubs. The ACC plant area offers a glimpse of the industry that powers the city — industrial visits on prior permission.",
    hero_image_url: null,
    tags: ["industrial tourism", "permission required"],
    timing: "By appointment",
    entry_fee: "N/A",
    best_time: "Weekdays",
    distance_km: 8,
    is_featured: false,
    avg_rating: 3.9,
    review_count: 12,
  },
  {
    id: "p9",
    slug: "central-library",
    name_en: "Central Library Satna",
    name_hi: "केंद्रीय पुस्तकालय",
    category: "education",
    description_en:
      "The district's main public library — reading rooms, competitive-exam section and a children's corner.",
    hero_image_url: null,
    tags: ["wifi", "study space"],
    timing: "9:00 AM – 8:00 PM",
    entry_fee: "Free (membership ₹100/yr)",
    best_time: "Weekday mornings",
    distance_km: 2,
    is_featured: false,
    avg_rating: 4.2,
    review_count: 51,
  },
  {
    id: "p10",
    slug: "district-collectorate",
    name_en: "District Collectorate",
    name_hi: "जिला कलेक्ट्रेट",
    category: "infrastructure",
    description_en:
      "The administrative heart of Satna district — collector office, public hearing (Jan Sunwai) every Tuesday.",
    hero_image_url: null,
    tags: ["govt office", "parking available"],
    timing: "10:30 AM – 5:30 PM (Mon–Fri)",
    entry_fee: "Free",
    best_time: "Tuesday Jan Sunwai",
    distance_km: 2.5,
    is_featured: false,
    avg_rating: 3.7,
    review_count: 23,
  },
];

export const seedRestaurants: Restaurant[] = [
  {
    id: "r1",
    slug: "krishna-dhaba",
    name_en: "Krishna Dhaba",
    name_hi: "कृष्णा ढाबा",
    cuisines: ["North Indian", "Dhabha"],
    veg_type: "veg",
    price_range: "budget",
    description:
      "Legendary NH-30 dhaba known for dal tadka, butter naan and truck-route portions. Family seating at the back.",
    hero_image_url: null,
    address: "NH-30, Bypass Road, Satna",
    phone: "07672-223344",
    distance_km: 4,
    open_time: "10:00",
    close_time: "23:00",
    is_featured: true,
    avg_rating: 4.5,
    review_count: 182,
  },
  {
    id: "r2",
    slug: "sharma-sweets",
    name_en: "Sharma Sweets & Namkeen",
    name_hi: "शर्मा स्वीट्स",
    cuisines: ["Sweets", "Chaat"],
    veg_type: "pure_veg",
    price_range: "budget",
    description:
      "The city's favourite for khoya peda, rasgulla and Sunday-morning jalebi-poha. Third-generation halwais.",
    hero_image_url: null,
    address: "Dhawari Chowk, Satna",
    phone: "07672-225566",
    distance_km: 1,
    open_time: "07:00",
    close_time: "22:00",
    is_featured: true,
    avg_rating: 4.7,
    review_count: 263,
  },
  {
    id: "r3",
    slug: "hotel-satna-restaurant",
    name_en: "Hotel Satna Restaurant",
    name_hi: "होटल सतना",
    cuisines: ["North Indian", "Chinese"],
    veg_type: "mixed",
    price_range: "mid",
    description:
      "The in-house multi-cuisine restaurant of Hotel Satna — AC family dining, thalis and Indo-Chinese.",
    hero_image_url: null,
    address: "Rewa Road, Satna",
    phone: "07672-227788",
    distance_km: 2,
    open_time: "11:00",
    close_time: "23:00",
    is_featured: true,
    avg_rating: 4.2,
    review_count: 145,
  },
  {
    id: "r4",
    slug: "bus-stand-chaat-corner",
    name_en: "Famous Chaat Corner",
    name_hi: "फेमस चाट कॉर्नर",
    cuisines: ["Chaat"],
    veg_type: "pure_veg",
    price_range: "budget",
    description:
      "The iconic chaat stall near the bus stand — aloo tikki, golgappe and dahi-bhalla since 1985.",
    hero_image_url: null,
    address: "Near Bus Stand, Satna",
    phone: null,
    distance_km: 1.2,
    open_time: "15:00",
    close_time: "22:00",
    is_featured: false,
    avg_rating: 4.6,
    review_count: 198,
  },
  {
    id: "r5",
    slug: "madhuram-thali",
    name_en: "Madhuram Pure Veg Thali",
    name_hi: "मधुरम थाली",
    cuisines: ["North Indian"],
    veg_type: "pure_veg",
    price_range: "mid",
    description:
      "Unlimited Rajasthani-MP style thali — 4 sabzi, dal-baati on Sundays, warm service.",
    hero_image_url: null,
    address: "Civil Lines, Satna",
    phone: "07672-229911",
    distance_km: 1.8,
    open_time: "11:30",
    close_time: "22:30",
    is_featured: true,
    avg_rating: 4.4,
    review_count: 121,
  },
  {
    id: "r6",
    slug: "annapurna-bhojnalaya",
    name_en: "Annapurna Bhojnalaya",
    name_hi: "अन्नपूर्णा भोजनालय",
    cuisines: ["North Indian", "Dhabha"],
    veg_type: "veg",
    price_range: "budget",
    description:
      "Simple, homely bhojnalaya near the station — fixed thali ₹80, fast service for travellers.",
    hero_image_url: null,
    address: "Station Road, Satna",
    phone: null,
    distance_km: 0.8,
    open_time: "09:00",
    close_time: "22:00",
    is_featured: false,
    avg_rating: 4.0,
    review_count: 76,
  },
  {
    id: "r7",
    slug: "zaika-family-restaurant",
    name_en: "Zaika Family Restaurant",
    name_hi: "ज़ायका",
    cuisines: ["North Indian", "Chinese", "South Indian"],
    veg_type: "mixed",
    price_range: "mid",
    description:
      "Popular family restaurant — biryani, tandoori and a separate veg kitchen.",
    hero_image_url: null,
    address: "Panna Naka, Satna",
    phone: "07672-233221",
    distance_km: 2.5,
    open_time: "11:00",
    close_time: "23:00",
    is_featured: false,
    avg_rating: 4.1,
    review_count: 98,
  },
  {
    id: "r8",
    slug: "jain-bhojan-griha",
    name_en: "Jain Bhojan Griha",
    name_hi: "जैन भोजन गृह",
    cuisines: ["North Indian"],
    veg_type: "jain",
    price_range: "budget",
    description:
      "Strictly Jain kitchen — no onion, no garlic, no root vegetables. Thali and farsan.",
    hero_image_url: null,
    address: "Mukhtiyarganj, Satna",
    phone: null,
    distance_km: 1.5,
    open_time: "10:00",
    close_time: "21:30",
    is_featured: false,
    avg_rating: 4.3,
    review_count: 54,
  },
  {
    id: "r9",
    slug: "highway-king-dhaba",
    name_en: "Highway King Dhaba",
    name_hi: "हाईवे किंग ढाबा",
    cuisines: ["North Indian", "Dhabha"],
    veg_type: "mixed",
    price_range: "budget",
    description:
      "Late-night NH-30 dhaba — paneer butter masala, charpai seating, open till 1 AM.",
    hero_image_url: null,
    address: "NH-30 near Sherganj, Satna",
    phone: null,
    distance_km: 6,
    open_time: "11:00",
    close_time: "01:00",
    is_featured: false,
    avg_rating: 4.2,
    review_count: 88,
  },
  {
    id: "r10",
    slug: "maihar-prasad-bhandar",
    name_en: "Maihar Prasad & Sweets Bhandar",
    name_hi: "मैहर प्रसाद भंडार",
    cuisines: ["Sweets"],
    veg_type: "pure_veg",
    price_range: "budget",
    description:
      "At the base of Maihar temple — famous for besan laddoo prasad and kalakand.",
    hero_image_url: null,
    address: "Temple Road, Maihar",
    phone: null,
    distance_km: 35,
    open_time: "05:00",
    close_time: "21:00",
    is_featured: false,
    avg_rating: 4.5,
    review_count: 67,
  },
];

export const seedMenuItems: MenuItem[] = [
  { id: "m1", restaurant_id: "r1", category: "Main", name: "Dal Tadka", description: "Signature smoky tadka dal", price: 120, is_veg: true },
  { id: "m2", restaurant_id: "r1", category: "Main", name: "Paneer Butter Masala", description: "Rich tomato gravy", price: 180, is_veg: true },
  { id: "m3", restaurant_id: "r1", category: "Breads", name: "Butter Naan", description: "Tandoor fresh", price: 35, is_veg: true },
  { id: "m4", restaurant_id: "r1", category: "Drinks", name: "Lassi", description: "Sweet, malai-topped", price: 60, is_veg: true },
  { id: "m5", restaurant_id: "r2", category: "Sweets", name: "Khoya Peda", description: "Local speciality, per kg", price: 480, is_veg: true },
  { id: "m6", restaurant_id: "r2", category: "Sweets", name: "Jalebi", description: "Sunday mornings, per kg", price: 240, is_veg: true },
  { id: "m7", restaurant_id: "r2", category: "Starters", name: "Samosa", description: "With chhole", price: 20, is_veg: true },
  { id: "m8", restaurant_id: "r3", category: "Main", name: "Veg Thali", description: "3 sabzi, dal, rice, roti, sweet", price: 220, is_veg: true },
  { id: "m9", restaurant_id: "r3", category: "Main", name: "Chicken Curry", description: "Home style", price: 280, is_veg: false },
  { id: "m10", restaurant_id: "r3", category: "Starters", name: "Veg Manchurian", description: "Indo-Chinese", price: 160, is_veg: true },
  { id: "m11", restaurant_id: "r5", category: "Main", name: "Unlimited Thali", description: "4 sabzi, dal, baati on Sundays", price: 250, is_veg: true },
  { id: "m12", restaurant_id: "r4", category: "Starters", name: "Aloo Tikki", description: "2 pc with chutneys", price: 40, is_veg: true },
  { id: "m13", restaurant_id: "r4", category: "Starters", name: "Golgappe", description: "6 pc, spicy pani", price: 30, is_veg: true },
];

export const seedEvents: CityEvent[] = [
  {
    id: "e1",
    title_en: "Maihar Mela 2026",
    title_hi: "मैहर मेला २०२६",
    category: "religious",
    venue: "Maihar, Sharda Devi Temple",
    description:
      "The grand Navratri mela at Maihar — lakhs of pilgrims, special ropeway hours, cultural programs.",
    starts_at: "2026-06-24T05:00:00+05:30",
    ends_at: "2026-07-02T22:00:00+05:30",
    is_featured: true,
  },
  {
    id: "e2",
    title_en: "District Cricket Tournament",
    title_hi: "जिला क्रिकेट टूर्नामेंट",
    category: "sports",
    venue: "Stadium Ground, Satna",
    description: "Inter-ward T20 tournament — register your team.",
    starts_at: "2026-07-05T08:00:00+05:30",
    ends_at: "2026-07-12T18:00:00+05:30",
    is_featured: false,
  },
  {
    id: "e3",
    title_en: "Satna Trade Fair",
    title_hi: "सतना व्यापार मेला",
    category: "trade",
    venue: "Exhibition Ground, Satna",
    description: "Annual trade fair — local businesses, food stalls, rides.",
    starts_at: "2026-07-10T10:00:00+05:30",
    ends_at: "2026-07-20T22:00:00+05:30",
    is_featured: false,
  },
  {
    id: "e4",
    title_en: "Independence Day Parade",
    title_hi: "स्वतंत्रता दिवस परेड",
    category: "civic",
    venue: "Police Parade Ground",
    description: "District-level flag hoisting and parade.",
    starts_at: "2026-08-15T08:00:00+05:30",
    ends_at: "2026-08-15T11:00:00+05:30",
    is_featured: false,
  },
  {
    id: "e5",
    title_en: "Sharad Navratri Garba Nights",
    title_hi: "शरद नवरात्रि गरबा",
    category: "cultural",
    venue: "Town Hall, Satna",
    description: "Community garba and dandiya evenings.",
    starts_at: "2026-10-11T19:00:00+05:30",
    ends_at: "2026-10-19T23:00:00+05:30",
    is_featured: false,
  },
];

export const seedReviews: Review[] = [
  { id: "v1", subject_type: "restaurant", subject_id: "r1", username: "Amit K.", rating: 5, body: "Best dal tadka on NH-30. Portions are huge, go hungry!", created_at: "2026-06-02T13:00:00+05:30" },
  { id: "v2", subject_type: "restaurant", subject_id: "r1", username: "Pooja S.", rating: 4, body: "Good food, gets crowded after 8 PM. Family section is clean.", created_at: "2026-05-28T20:30:00+05:30" },
  { id: "v3", subject_type: "restaurant", subject_id: "r2", username: "Ravi T.", rating: 5, body: "Khoya peda yahan ka sabse best hai. Sunday jalebi must try.", created_at: "2026-06-05T09:00:00+05:30" },
  { id: "v4", subject_type: "restaurant", subject_id: "r3", username: "Neha M.", rating: 4, body: "AC dining, decent thali. Manchurian was good too.", created_at: "2026-05-20T21:00:00+05:30" },
  { id: "v5", subject_type: "restaurant", subject_id: "r4", username: "Sandeep V.", rating: 5, body: "35 saal se same taste. Golgappe ka pani teekha perfect.", created_at: "2026-06-07T18:00:00+05:30" },
];

export const seedLivePulse: LivePulseItem[] = [
  {
    id: "lp1",
    kind: "dining",
    text_en: "Rahul from Civil Lines is looking for lunch company at Krishna Dhaba",
    text_hi: "सिविल लाइन्स के राहुल कृष्णा ढाबा पर लंच साथी ढूंढ रहे हैं",
    meta: "Today 1:30 PM · 2 spots",
    href: "/discover?tab=dine",
  },
  {
    id: "lp2",
    kind: "cab",
    text_en: "Priya posted a cab share: Satna → Rewa tomorrow 9 AM",
    text_hi: "प्रिया ने कैब शेयर पोस्ट की: सतना → रीवा कल सुबह 9 बजे",
    meta: "2 seats · ₹150/person",
    href: "/discover?tab=cab",
  },
  {
    id: "lp3",
    kind: "photo",
    text_en: "New photo added to Maihar Devi",
    text_hi: "मैहर देवी में नई फोटो जुड़ी",
    meta: "12 minutes ago",
    href: "/discover?tab=places",
  },
];

export const heroBanners = [
  {
    id: "hb1",
    title_en: "Maihar Mela 2026 — 14 days to go",
    title_hi: "मैहर मेला २०२६ — १४ दिन बाकी",
    href: "/discover?tab=places",
    tone: "primary" as const,
  },
  {
    id: "hb2",
    title_en: "New: Bharhut Stupa Trail is live",
    title_hi: "नया: भरहुत स्तूप ट्रेल लाइव है",
    href: "/discover?tab=trails",
    tone: "heritage" as const,
  },
  {
    id: "hb3",
    title_en: "Community Alert: Water supply disruption in Ward 12",
    title_hi: "सामुदायिक अलर्ट: वार्ड 12 में जल आपूर्ति बाधित",
    href: "/community",
    tone: "danger" as const,
  },
];

export const todayThought = {
  hi: "अपना शहर वही है जहाँ दिल बसता है।",
  en: "Your city is where your heart lives.",
};

export const historyFact =
  "On this day in 1962, Bharhut Stupa fragments were officially catalogued by the ASI.";
